name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  job-example-1:
    runs-on: ubuntu-latest
    steps:
      - name: print a welcome message
        run: echo "welcome"
  job-example-2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v7

      - name: list folders
        run: ls -la
